version: '2'
services:
  db:
    image: postgres:9.3.15
  memcached:
    image: memcached:latest
  web:
    build: .
    command: bundle exec rails server --port 3000 --binding 0.0.0.0
    ports:
      - "3000:3000"
    links:
      - db
      - memcached
    environment:
      - POSTGRES_DB=coya_challenge_development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=coya
    volumes:
      - .:/coya_challenge
