version: '2'
services:
  db:
    image: postgres:9.3.15
  memcached:
    image: memcached:latest
  web:
    build: .
    command: bundle exec rails server
    ports:
      - "3000:3000"
    links:
      - db
      - memcached
    volumes:
      - .:/coya_challenge
